baseURL = 'https://cv.aws10.dcoletasix2a.cat/'
languageCode = 'en-us'
title = 'Cloud Resume Challenge'
theme = 'PaperMod'

[params]
    defaultTheme = "auto"
    ShowShareButtons = true
    ShowReadingTime = false
    
    [params.profileMode]
        enabled = true
        title = "Dani Colet"
        subtitle = "Cloud Engineer | DevOps Enthusiast"
        imageUrl = "https://github.com/DaniColet.png"
        imageTitle = "My Profile"
    [[params.profileMode.buttons]]
        name = "GitHub"
        url = "https://github.com/DaniColet"

    [[params.profileMode.buttons]]
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/daniel-colet"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/resume"
    weight = 2
